/**
 * Regressions for auto-generated edit rejection and error propagation.
 *
 * Generated-file protection is authoritative at edit execution: it must leave
 * the file untouched and return a tool error the model can correct, without
 * aborting the assistant turn from speculative streamed arguments.
 */

import { afterEach, beforeEach, expect, it } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import { EditTool } from "@oh-my-pi/pi-coding-agent/edit";
import type { ToolSession } from "@oh-my-pi/pi-coding-agent/tools";
import { removeSyncWithRetries, Snowflake } from "@oh-my-pi/pi-utils";

let tempDir: string;

beforeEach(() => {
	tempDir = path.join(os.tmpdir(), `pi-edit-regressions-${Snowflake.next()}`);
	fs.mkdirSync(tempDir, { recursive: true });
});

afterEach(async () => {
	if (tempDir) removeSyncWithRetries(tempDir);
});

it("auto-generated rejection remains tool-local when streaming abort is disabled", async () => {
	const generatedPath = path.join(tempDir, "generated.ts");
	const original = "// AUTO-GENERATED\nexport const x = 1;\n";
	await Bun.write(generatedPath, original);
	const session = {
		cwd: tempDir,
		hasUI: false,
		getSessionFile: () => null,
		getSessionSpawns: () => "*",
		getArtifactsDir: () => null,
		settings: Settings.isolated({
			"edit.mode": "patch",
			"edit.streamingAbort": false,
			"edit.blockAutoGenerated": true,
		}),
		enableLsp: false,
	} as ToolSession;
	const editTool = new EditTool(session, "patch");
	const result = await editTool.execute("generated-edit", {
		path: generatedPath,
		edits: [{ op: "update", diff: "@@\n-export const x = 1;\n+export const x = 2;\n" }],
	});

	expect(result.isError).toBe(true);
	const text = result.content.find(part => part.type === "text");
	expect(text?.type === "text" ? text.text : "").toContain("Cannot modify auto-generated file");
	expect(await Bun.file(generatedPath).text()).toBe(original);
});

it("multi-entry edit on an auto-generated file surfaces isError + error text instead of silently faking success", async () => {
	// Direct invocation of the patch-mode EditTool with two entries against an
	// auto-generated file. The orchestrator (executeSinglePathEntries) must NOT
	// swallow the per-entry errors — it must mark the aggregate result with
	// isError: true so the renderer takes the error branch instead of falling
	// through to the streaming preview (which displays the *proposed* diff and
	// looks identical to success).
	const generatedPath = path.join(tempDir, "generated.ts");
	await Bun.write(
		generatedPath,
		"// Code generated by sqlc. DO NOT EDIT.\nexport const foo = 1;\nexport const bar = 2;\n",
	);

	const originalVariant = Bun.env.PI_EDIT_VARIANT;
	Bun.env.PI_EDIT_VARIANT = "patch";

	try {
		const sessionFile = path.join(tempDir, "session.jsonl");
		const sessionDir = path.join(tempDir, "session");
		const session = {
			cwd: tempDir,
			hasUI: false,
			getSessionFile: () => sessionFile,
			getSessionSpawns: () => "*",
			getArtifactsDir: () => sessionDir,
			allocateOutputArtifact: async (toolType: string) => {
				fs.mkdirSync(sessionDir, { recursive: true });
				return { id: "a-1", path: path.join(sessionDir, `a-1.${toolType}.log`) };
			},
			settings: Settings.isolated({ "edit.blockAutoGenerated": true }),
			enableLsp: false,
		} as ToolSession;

		const editTool = new EditTool(session);
		const result = await editTool.execute("test-multi-entry", {
			path: generatedPath,
			edits: [
				{ op: "update", diff: "@@\n-export const foo = 1;\n+export const foo = 11;\n" },
				{ op: "update", diff: "@@\n-export const bar = 2;\n+export const bar = 22;\n" },
			],
		});

		// File is untouched on disk.
		const contentOnDisk = await Bun.file(generatedPath).text();
		expect(contentOnDisk).toContain("export const foo = 1;");
		expect(contentOnDisk).toContain("export const bar = 2;");

		// Aggregate result must signal an error so the renderer doesn't draw
		// the streaming preview as if it succeeded.
		expect(result.isError).toBe(true);

		// Native staging rejects the complete call before any entry is applied.
		const textPart = result.content.find(c => c.type === "text");
		const text = textPart?.type === "text" ? textPart.text : "";
		const occurrences = text.match(/Cannot modify auto-generated file/g) ?? [];
		expect(occurrences.length).toBe(1);

		// `details.diff` must not contain a fabricated diff that would mislead the
		// renderer's preview-fallback branch into showing the proposed change.
		const details = result.details as { diff?: string } | undefined;
		expect(details?.diff ?? "").toBe("");
	} finally {
		if (originalVariant === undefined) {
			delete Bun.env.PI_EDIT_VARIANT;
		} else {
			Bun.env.PI_EDIT_VARIANT = originalVariant;
		}
	}
});
